### ISSUE TITLE
Create a data model intro in top-level readme

### ISSUE THREAD

**Issue by stevewritescode** [docnetwork/api#22]
The individual pages are very helpful to understand requests/responses for specific entities.

It would be great to have a few sentences at https://github.com/docnetwork/api/blob/master/v2/README.md that explain at a high-level how the entities interact and generally what sort of information they contain.

@nronnei explained some of the detail to me earlier (thanks!) - as I get more familiar with the API I can contribute a draft of this intro.

**Comment by nronnei** [comment]
@stevewritescode great suggestion; I've been hearing this more and more. I'll see if we can get something in the works to address this.
