### ISSUE TITLE
GET users response is missing phone and location fields

### ISSUE THREAD

**Issue by stevewritescode** [docnetwork/api#26]
I cannot retrieve`phone` or `location` fields in the GET call for [users](https://github.com/docnetwork/api/blob/master/v2/chapters/users.md#get-a-profiles-users):

`GET /v2/organizations/{orgID}/profiles/{profileID}/users`

The docs mention these fields, but I'm not clear on how to retrieve them since the GET response does not include them. I've confirmed via the web UI that there are many users in my organization with phone numbers and locations set, but I do not see it in the API responses.

The [contributing](https://github.com/docnetwork/api/blob/master/CONTRIBUTING.md) guide asks for a `X-Request-Identifier` header examples in bug requests, but I do not see that response header. I do see a `CF-RAY` value, which might still serve the same purpose for you? Here's an example:

`CF-RAY: 6df99b0aef138c48-EWR`

Thank you!

**Comment by nronnei** [comment]
Hey, @stevewritescode, thanks for that. You're correct—we don't send those back with a `GET` right now. Can you tell me about your desired use case? If you prefer, you can reach out to me directly via email.

**Comment by stevewritescode** [comment]
Thanks for the reply! I'm happy to share two use-cases:

For `location` - Our summer programs are spread across several different cities in several regions of the United States. For reporting purposes, we group our programs together via regions based on their location - e.g. the Boston and Portland programs are categorized as part of the Northeast region. Similarly, we would like to incorporate into our reporting comparisons between our program locations and the locations of our applicants / enrolled participants. The plans was to use this `location` field on the user accounts to better understand how users are reporting their locations. There's another layer of complexity that I'll mention as well - in some circumstances (depending on the age of the participant) we prefer address information shared as part of the registration questions/answers instead, but in other circumstances we are planning to reference this user `location` field.

For `phone` - Our staff is reviewing information about applications and enrollments on a daily basis. Given the participants population that we serve, regular follow-up is often needed to ensure people are completing the applications in a timely manner. We're planning to pull these phone numbers in various reports for our staff to reference to call certain sets of applicants to help them complete or otherwise clarify their application.

The `All Users` standard report available in the web interface contains this information, but it's a little tricky to download programmatically... and of course I'm sure that the official API is more stable and supported. FWIW, we load this data into several backend locations include a relational database, google sheets, and a custom web app used by our staff.

**Comment by stevewritescode** [comment]
Thanks for the update!!

**Comment by AlienBob93** [comment]
@stevewritescode `phone` or `location` fields in now available when making a GET call for [users](https://github.com/docnetwork/api/blob/master/v2/chapters/users.md#get-a-profiles-users):
